name: "Setup Node, yarn and cache"
description: "Setup node, enable yarn with corepack and activate cache"

inputs:
  node-version:
    description: "Node's version to use (cf: actions/setup-node)"
    required: false
    default: lts/*

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{inputs.node-version}}

    - name: Activate Yarn
      shell: bash
      run: corepack enable
